### ISSUE TITLE
Failed to load the wrap-style package

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [raccy/atom-wrap-style#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Unknown Windows Version
**Thrown From**: [wrap-style](https://github.com/raccy/atom-wrap-style) package, v0.2.0
### Stack Trace

Failed to load the wrap-style package

```
At Cannot find module 'src/tokenized-line'

Error: Cannot find module 'src/tokenized-line'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/wrap-style/lib/wrap-style-manager.coffee:2:17)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/wrap-style/lib/wrap-style-manager.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/wrap-style/lib/wrap-style.coffee:1:20)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/wrap-style/lib/wrap-style.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:661:34)
    at C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:115:28
    at Package.module.exports.Package.measure (C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package-manager.js:434:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\src\package-manager.js:511:30)
    at C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:444:29
    at exit (C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.2.0\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```
### Commands

```
     -1:33.1.0 settings-view:open (atom-text-editor.editor.is-focused)
     -1:27 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:26 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:59.4.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:58.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-monokai"
    ]
  },
  "wrap-style": {
    "style": {
      "wordBreak": "break-all"
    }
  }
}
```
### Installed Packages

``` coffee
# User
atom-monokai, v0.9.6
autoclose-html, v0.19.0
editorconfig, v1.2.2
file-icons, v1.6.11
go-plus, v3.5.1
highlight-line, v0.11.0
open-recent, v4.0.1
quick-highlight, v0.3.7
show-ideographic-space, v1.0.1
symbols-tree-view, v0.10.1
tablr, v0.6.1
wrap-style, v0.2.0

# Dev
No dev packages
```

**Comment by raccy** [comment]
v1.2.0 changed loading Atom's core source directly, uses asar.
I'll change the way to load it... wait a moment.
