### ISSUE TITLE
Incompatible with Atom 1.9

### ISSUE THREAD

**Issue by lalomartins** [raccy/atom-wrap-style#4]
Starting Atom 1.9 with the package enabled:

**Atom Version**: 1.9.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [wrap-style](https://github.com/raccy/atom-wrap-style) package, v0.3.1
### Stack Trace

Failed to activate the wrap-style package

```
At Cannot find module 'C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src/display-buffer'

Error: Cannot find module 'C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src/display-buffer'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Lalo/.atom/packages/wrap-style/lib/wrap-style-manager.coffee:2:17)
    at Object.<anonymous> (file:///C:/Users/Lalo/.atom/packages/wrap-style/lib/wrap-style-manager.coffee:1:1)
    at Module._compile (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Lalo/.atom/packages/wrap-style/lib/wrap-style.coffee:1:20)
    at Object.<anonymous> (file:///C:/Users/Lalo/.atom/packages/wrap-style/lib/wrap-style.coffee:1:1)
    at Module._compile (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package.js:173:16)
    at C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package.js:156:32
    at Package.module.exports.Package.measure (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package.js:92:15)
    at C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package.js:149:26
    at Package.module.exports.Package.activate (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package-manager.js:538:21)
    at C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (C:\Users\Lalo\AppData\Local\atom\app-1.9.0\resources\app.asar\src\config.js:337:18)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "meteor-api",
      "autosave",
      "autocomplete-snippets",
      "opened-files",
      "tree-view",
      "wrap-guide",
      "atom-ctags",
      "meteor-helper",
      "quantum-shell",
      "language-spacebars",
      "titanium-build",
      "titanium-language-javascript"
    ],
    "ignoredNames": [
      ".git",
      ".bzr",
      ".DS_Store",
      "Thumbs.db"
    ],
    "themes": [
      "atom-material-ui",
      "atom-spring-green-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.16.3 (inactive)
angular-2-typeScript-snippets, v0.4.6 (inactive)
atom-ctags, v4.5.2 (inactive)
atom-material-syntax-light, v0.4.5 (inactive)
atom-material-ui, v1.3.3 (inactive)
atom-spring-green-syntax, v1.1.12 (inactive)
atom-typescript, v10.1.5 (inactive)
autocomplete-ionic2-framework, v0.3.2 (inactive)
build, v0.65.0 (inactive)
busy, v0.6.0 (inactive)
caniuse, v0.9.0 (inactive)
climate-syntax, v5.0.0 (inactive)
conamour-syntax, v0.1.0 (inactive)
duotone-carrots-syntax, v0.2.0 (inactive)
fonts-cjk, v0.1.2 (inactive)
git-plus, v5.16.2 (inactive)
hard-wrap, v1.0.1 (inactive)
Hyrule-atom, v1.1.0 (inactive)
imdone-atom, v1.3.29 (inactive)
language-cjsx, v0.3.0 (inactive)
language-gherkin, v1.0.4 (inactive)
language-jade, v0.7.1 (inactive)
language-javascript-jsx, v0.3.7 (inactive)
language-nginx, v0.6.1 (inactive)
language-postcss, v1.2.3 (inactive)
language-spacebars, v0.2.2 (inactive)
leet-syntax, v1.0.0 (inactive)
linter, v1.11.14 (inactive)
linter-csslint, v1.3.2 (inactive)
linter-eslint, v7.2.4 (inactive)
meteor-api, v2.20.0 (inactive)
meteor-helper, v0.28.0 (inactive)
multi-wrap-guide, v0.25.1 (inactive)
open-recent, v5.0.0 (inactive)
opened-files, v0.3.6 (inactive)
piatto-light, v2.0.2 (inactive)
quantum-shell, v0.7.1 (inactive)
recent-files-fuzzy-finder, v0.2.4 (inactive)
rectangle-selection, v0.2.0 (inactive)
resize-indent, v0.3.0 (inactive)
revert-buffer, v0.5.0 (inactive)
script, v3.8.3 (inactive)
source-preview-react, v0.2.0 (inactive)
Stylus, v3.0.0 (inactive)
swap-selection, v0.4.0 (inactive)
tab-control, v0.6.9 (inactive)
theme-switcher, v1.1.0 (inactive)
tishadow, v0.1.1 (inactive)
titan-framework-snippets, v0.7.0 (inactive)
titanium-build, v0.8.1 (inactive)
titanium-language-javascript, v0.48.0 (inactive)
unicorn-light-ui, v2.1.0 (inactive)
unicorn-ui, v1.2.0 (inactive)
viriato, v0.12.0 (inactive)
vs-blue-ui, v0.1.2 (inactive)
wordcount, v2.6.2 (inactive)
wrap-style, v0.3.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.38.1 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.0 (inactive)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by ex-jedi** [comment]
Same here...

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.4
**System**: Microsoft Windows 10 Home
**Thrown From**: [wrap-style](https://github.com/raccy/atom-wrap-style) package, v0.3.1

### Stack Trace

Failed to load the wrap-style package

```
At Cannot find module 'C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src/display-buffer'

Error: Cannot find module 'C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src/display-buffer'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Mark/.atom/packages/wrap-style/lib/wrap-style-manager.coffee:2:17)
    at Object.<anonymous> (file:///C:/Users/Mark/.atom/packages/wrap-style/lib/wrap-style-manager.coffee:1:1)
    at Module._compile (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Mark/.atom/packages/wrap-style/lib/wrap-style.coffee:1:20)
    at Object.<anonymous> (file:///C:/Users/Mark/.atom/packages/wrap-style/lib/wrap-style.coffee:1:1)
    at Module._compile (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package.js:715:27)
    at C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package-manager.js:457:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\package-manager.js:536:30)
    at C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:452:29
    at exit (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\Mark\AppData\Local\atom\app-1.9.4\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

### Commands

```
     -3:04.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -2:45.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:29.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:02.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:02.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:02.4.0 core:paste (atom-text-editor.editor.is-focused)
     -1:00.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:59.4.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:57.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:51.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:44.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:39.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:39.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "deprecation-cop",
      "wrap-guide",
      "linter-sass-lint",
      "AtomicChar"
    ],
    "themes": [
      "seti-ui",
      "monokai-seti"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (inactive)
atom-bracket-highlight, v0.3.1 (active)
atom-color-highlight, v3.0.9 (active)
AtomicChar, v0.3.11 (inactive)
block-cursor, v0.13.1 (active)
color-picker, v2.2.2 (active)
css-snippets, v0.9.0 (active)
emmet, v2.4.3 (active)
emmet-snippets-compatibility, v1.0.6 (active)
highlight-selected, v0.11.2 (active)
jshint, v1.8.5 (active)
linter, v1.11.14 (active)
linter-htmlhint, v1.3.0 (active)
linter-scss-lint, v3.0.4 (active)
minimap, v4.24.7 (active)
minimap-autohide, v0.10.1 (active)
minimap-bookmarks, v0.3.1 (active)
minimap-codeglance, v0.4.5 (active)
minimap-cursorline, v0.2.0 (active)
minimap-find-and-replace, v4.5.1 (active)
minimap-git-diff, v4.3.1 (active)
minimap-selection, v4.4.0 (active)
monokai, v0.18.0 (inactive)
monokai-seti, v0.7.0 (active)
open-in-browser, v0.4.7 (inactive)
open-recent, v5.0.0 (active)
pigments, v0.31.2 (active)
project-manager, v2.9.7 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (active)
swackets, v0.10.0 (active)
wrap-style, v0.3.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.2 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.0 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by raccy** [comment]
I see.
Maybe the `display-buffer` was deleted in Atom 1.9. So I try to find a way to hack word-wrap...
